apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-server
  namespace: nfs-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nfs-server
  template:
    metadata:
      annotations:

      labels:
        app: nfs-server
    spec:
      containers:
        - name: nfs-server
          image: erichough/nfs-server:latest
          ports:
            - name: nfsv4
              containerPort: 2049

          volumeMounts:
            - mountPath: /cameras
              name: nfs-server-mount

          resources:
            requests:
              memory: "256Mi"
              cpu: "2"
            limits:
              memory: "4096Mi"
              cpu: "4"
      volumes:
        - name: nfs-server-mount
          persistentVolumeClaim:
            claimName: nfs-server-pvc
