apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-server
  namespace: nfs-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nfs-server
  template:
    metadata:
      labels:
        app: nfs-server
    spec:
      containers:
        - name: nfs-server
          image: itsthenetwork/nfs-server-alpine:latest-arm

          env:
            - name: SHARED_DIRECTORY
              value: /home/cameras

          ports:
            - containerPort: 2049
              name: nfsd

            - containerPort: 111
              name: mapper

          volumeMounts:
            - mountPath: /home/cameras
              name: nfs-server-mount

          securityContext:
            privileged: True

          resources:
            requests:
              memory: "256Mi"
              cpu: "2"
            limits:
              memory: "512Mi"
              cpu: "4"

      volumes:
        - name: nfs-server-mount
          persistentVolumeClaim:
            claimName: nfs-server-pvc
