persistentVolumeClaim:
  enabled: true

ingress:
  enabled: true

sserviceTCP:
  loadBalancerIP: 192.168.0.6
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-svc

serviceUDP:
  loadBalancerIP: 192.168.0.6
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-svc
