persistentVolumeClaim:
  enabled: true

ingress:
  enabled: true

serviceWeb:
  type: LoadBalancer
  loadBalancerIP: 192.168.0.6
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-svc

serviceDns:
  type: LoadBalancer
  loadBalancerIP: 192.168.0.6
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-svc
