ingress:
  enabled: true

persistentVolumeClaim:
  enabled: true

serviceWeb:
  loadBalancerIP: 192.168.0.6
  annotations:
    metallb.io/address-pool: default-pool
    metallb.io/allow-shared-ip: pihole-svc
  type: LoadBalancer

serviceDns:
  loadBalancerIP: 192.168.0.6
  annotations:
    metallb.io/address-pool: default-pool
    metallb.io/allow-shared-ip: pihole-svc
  type: LoadBalancer

serviceTCP:
  loadBalancerIP: 192.168.0.6
  annotations:
    metallb.io/address-pool: default-pool
    metallb.io/allow-shared-ip: pihole-svc
  type: LoadBalancer

serviceUDP:
  loadBalancerIP: 192.168.0.6
  annotations:
    metallb.io/address-pool: default-pool
    metallb.io/allow-shared-ip: pihole-svc
  type: LoadBalancer
