persistentVolumeClaim:
  enabled: true

ingress:
  enabled: true

serviceWeb:
  annotations:
    metallb.io/address-pool: default-pool
  type: LoadBalancer

serviceDns:
  annotations:
    metallb.io/address-pool: default-pool
  type: LoadBalancer
