# will create kubernees ingress
ingress:
  enabled: true
  hosts:
    - pihole-k3s.local

# will create kubernetes services for web admin
serviceWeb:
  annotations:
    metallb.io/allow-shared-ip: pihole-svc
    metallb.io/loadBalancerIPs: 192.168.0.6
  type: LoadBalancer

# will set your admin password for the web inteface
adminPassword: "*****"

# create a kubernetes service and expose
# port 53 outside of cluster on the local network
serviceDns:
  annotations:
    metallb.io/allow-shared-ip: pihole-svc
    metallb.io/loadBalancerIPs: 192.168.0.6
  type: LoadBalancer

serviceDhcp:
  annotations:
    metallb.io/allow-shared-ip: pihole-svc
    metallb.io/loadBalancerIPs: 192.168.0.6
  type: LoadBalancer
