persistentVolumeClaim:
  enabled: true

ingress:
  enabled: true

serviceWeb:
  annotations:
    metallb.io/loadBalancerIPs: 192.168.0.6
    metallb.universe.tf/allow-shared-ip: pihole-svc

serviceDns:
  annotations:
    metallb.io/loadBalancerIPs: 192.168.0.6
    metallb.universe.tf/allow-shared-ip: pihole-svc
